#Settings and configurations of project

LANGSMITH_TRACING=true

LANGSMITH_API_KEY=***REMOVED***

ANTHROPIC_API_KEY=***REMOVED***

LANGSMITH_PROJECT=netops-agents

AWS_REGION=us-east-2
S3_LAKE_BUCKET=s3-models-data-lake-639852019131-us-east-2-an
ATHENA_OUTPUT=